version: '3'

services:
  db:
    image: ghcr.io/railwayapp-templates/postgres-ssl
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ISP_DB
    volumes:
      - ./postgres:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: isp-aprendiendo-juntos
    container_name: ISP_MONGO
    volumes:
      - ./mongo:/data/db