version: '3'

services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: BACKEND_POSTGRES
    volumes:
      - ./postgres:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGODB_DATABASE: ${MONGO_DB}
    container_name: BACKEND_MONGO
    volumes:
      - ./mongo:/data/db